# © 2026 The Johns Hopkins University Applied Physics Laboratory LLC
from slippage_model_utils.r_script_wrapper import RVariableCreator
import pandas as pd
from pathlib import Path
import re
from typing import Dict


def build_shortest_name_lookup(producer_group_mapping: pd.DataFrame) -> Dict[str, str]:
    """
    For each group in producer_group_mapping, find the shortest 'name' string.

    Returns:
        dict: {group_value_as_str -> shortest_name}
    """
    # Ensure required columns exist
    required = {"name", "group"}
    missing = required - set(producer_group_mapping.columns)
    if missing:
        raise ValueError(f"producer_group_mapping missing columns: {missing}")

    # Drop NA in required columns
    pgm = producer_group_mapping.dropna(subset=["name", "group"]).copy()

    # Coerce 'group' to string to standardize key type
    pgm["group_str"] = pgm["group"].astype(str)

    # Compute length of name and pick shortest per group_str
    shortest = (
        pgm.assign(name_len=pgm["name"].astype(str).str.len())
           .sort_values(["group_str", "name_len", "name"])
           .drop_duplicates(subset=["group_str"], keep="first")
    )

    # Build mapping: group_str -> name
    return dict(zip(shortest["group_str"], shortest["name"]))


def map_group_to_shortest_name(
    synth_data: pd.DataFrame,
    group_col: str,
    producer_group_mapping: pd.DataFrame,
    output_col: str = None,
    default_value: str = "Reference",
) -> pd.DataFrame:
    """
    Map group IDs in synth_data[group_col] to the shortest 'name' for that group
    from producer_group_mapping, with type harmonization and a default for missing.

    Args:
        synth_data: DataFrame with a column of group IDs (e.g., 'PRODUCER_GROUP_TOP').
        group_col: Column in synth_data that contains group values (numeric or string).
        producer_group_mapping: DataFrame with 'name' and 'group' columns.
        output_col: Name of the output column. If None, overwrites group_col.
        default_value: Value to use when group_col value is not found in mapping
                      (e.g., "Reference").

    Returns:
        Updated synth_data with the mapped column added/overwritten.
    """
    if group_col not in synth_data.columns:
        raise ValueError(f"{group_col} not found in synth_data")

    # Build lookup {group_str -> shortest name}
    group_to_shortest_name = build_shortest_name_lookup(producer_group_mapping)

    # Determine target column name
    if output_col is None:
        output_col = group_col

    # Coerce group_col to string to align with mapping keys
    group_values_str = synth_data[group_col].astype(str)

    # Map; values not found will become NaN
    mapped = group_values_str.map(group_to_shortest_name)

    # Fill missing mappings with default_value (e.g. "Reference")
    mapped = mapped.fillna(default_value)

    synth_data[output_col] = mapped

    return synth_data



def create_engineered_features(
    synth_data: pd.DataFrame = None,
    dt_train: pd.DataFrame =None,
    producer_group_mapping: pd.DataFrame=None,
) -> pd.DataFrame:

    if synth_data is None:
        raise ValueError('Synthetic Data Passed is None')


    print(f'\nCreating Engineered Features...')

    print(f'   Creating features generated by the R script')
    # Create features from the R script using the R wrapper
    creator = RVariableCreator()

    print(f'      Creating PRODUCER_GROUP_TOP feature')
    synth_data = creator.generate_producer_top_strata_features(
        df=synth_data,
        dt_train=dt_train,
        max_strat_count=50,
        min_action_rate=0.02,
        min_records=5,
        use_parquet=False,
    )

    print(f'      Creating IMPORTER_NAME_TOP feature')
    synth_data = creator.generate_importer_top_strata_features(
        df=synth_data,
        dt_train=dt_train,
        max_strat_count=50,
        min_action_rate=0.02,
        min_records=5,
        use_parquet=False,
    )

    print(f'      Creating Quantity Binary Features')
    # Fall back to CSV if needed (smaller data, compatibility)
    key_col = "RISK_UNIT"
    quantity_binary_variables = creator.generate_quantity_binaries(
        df=synth_data,
        quantity_threshold=200,
        group_cols=[key_col],
        use_parquet=False
    )

    # Identify non-key columns coming from quantity_binary_variables
    new_cols = [c for c in quantity_binary_variables.columns if c != key_col]

    # Drop any of those columns from synth_data if they already exist
    cols_to_drop = [c for c in new_cols if c in synth_data.columns]
    if cols_to_drop:
        synth_data = synth_data.drop(columns=cols_to_drop)

    # 4. Merge – no name conflict → no _x/_y suffixes
    # TODO: Avoid using merge for larger dataframes
    synth_data = synth_data.merge(
        quantity_binary_variables,
        on=key_col,
        how='left',
    )

    print(f'      Done')

    return synth_data
