# © 2026 The Johns Hopkins University Applied Physics Laboratory LLC
from slippage_model_utils.r_script_wrapper import RVariableCreator
import pandas as pd
from pathlib import Path
import re


def create_engineered_features(
    synth_data: pd.DataFrame = None,
    producer_group_mapping: pd.DataFrame=None,
) -> pd.DataFrame:

    if synth_data is None:
        raise ValueError('Synthetic Data Passed is None')


    print(f'\nCreating Engineered Features...')

    print(f'   Creating features generated by the R script')
    # Create features from the R script using the R wrapper
    creator = RVariableCreator()

    print(f'      Cleaning Producer Name')
    # Create a raw IMPORTER_NAME column with the original importer name
    synth_data['PRODUCER_NAME_RAW'] = synth_data['PRODUCER_NAME']

    # Update the IMPORTER_NAME column with the cleaned version.
    synth_data['PRODUCER_NAME1'] = creator.batch_basic_text_preproc(synth_data['PRODUCER_NAME_RAW'])


    producer_group_mapping = producer_group_mapping.rename(
        columns={"PRODUCER_NAME": "name", "grouping": "group"}
    )

    print(f'   Creating producer group mappings')
    synth_data = creator.entity_resolution(
        df=synth_data,
        entity_resolution_lookup_table=producer_group_mapping,
        use_parquet=False,  # or True, as you prefer
    )

    synth_data = creator.generate_producer_top_strata_features(
        df=synth_data,
        max_strat_count=50,
        min_action_rate=-1.0,
        min_records=10,
        use_parquet=False,
    )

    print(f'      Cleaning Importer Name')
    # Create a raw IMPORTER_NAME column with the original importer name
    synth_data['IMPORTER_NAME_RAW'] = synth_data['IMPORTER_NAME']

    # Update the IMPORTER_NAME column with the cleaned version.
    synth_data['IMPORTER_NAME1'] = creator.batch_basic_text_preproc(synth_data['IMPORTER_NAME_RAW'])

    synth_data = creator.generate_importer_top_strata_features(
        df=synth_data,
        max_strat_count=50,
        min_action_rate=-1.0,
        min_records=10,
        use_parquet=False,
    )

    print(f'      Creating Quantity Binary Features')
    # Fall back to CSV if needed (smaller data, compatibility)
    key_col = "RISK_UNIT"
    quantity_binary_variables = creator.generate_quantity_binaries(
        df=synth_data,
        quantity_threshold=200,
        group_cols=[key_col],
        use_parquet=False
    )

    # Identify non-key columns coming from quantity_binary_variables
    new_cols = [c for c in quantity_binary_variables.columns if c != key_col]

    # Drop any of those columns from synth_data if they already exist
    cols_to_drop = [c for c in new_cols if c in synth_data.columns]
    if cols_to_drop:
        synth_data = synth_data.drop(columns=cols_to_drop)

    # 4. Merge – no name conflict → no _x/_y suffixes
    synth_data = synth_data.merge(
        quantity_binary_variables,
        on=key_col,
        how='left',
    )

    print(f'      Done')

    return synth_data
