# © 2026 The Johns Hopkins University Applied Physics Laboratory LLC
from slippage_model_utils.r_script_wrapper import RVariableCreator
import pandas as pd
from typing import Dict, Optional


def create_engineered_features(
    synth_data: pd.DataFrame = None,
    dt_train: pd.DataFrame = None,
    producer_group_mapping: pd.DataFrame = None,
    status: Optional["st.delta_generator.DeltaGenerator"] = None,
) -> pd.DataFrame:
    """Create engineered features for synthetic PIS/RBS data.

    This function:

    1. Validates that ``synth_data`` is provided.
    2. Uses the R-based ``RVariableCreator`` to generate:
       * ``PRODUCER_GROUP_TOP`` strata features,
       * ``IMPORTER_NAME_TOP`` strata features,
       * binary quantity features per risk unit.
    3. Merges the generated quantity-binary features into ``synth_data``,
       after dropping any existing conflicting columns.

    Args:
        synth_data: Synthetic data DataFrame with risk-unit level records.
        dt_train: Training DataFrame used by the R script for strata feature
            generation.
        producer_group_mapping: Optional producer grouping DataFrame (not used
            directly here but may be required upstream).

    Returns:
        Updated ``synth_data`` DataFrame with engineered features added.

    Raises:
        ValueError: If ``synth_data`` is None.
    """

    # Logger for GUI
    def log(msg: str):
        if status is not None:
            status.write(msg)
        else:
            print(msg)

    if synth_data is None:
        raise ValueError('Synthetic Data Passed is None')

    print(f'\nCreating Engineered Features...')

    print(f'   Creating features generated by the R script')
    if status is not None: log(f'---Creating features generated by the R script')
    # Create features from the R script using the R wrapper
    creator = RVariableCreator()

    print(f'      Creating PRODUCER_GROUP_TOP feature')
    if status is not None: log(f'------Creating PRODUCER_GROUP_TOP feature')
    synth_data = creator.generate_producer_top_strata_features(
        df=synth_data,
        dt_train=dt_train,
        max_strat_count=50,
        min_action_rate=0.02,
        min_records=5,
        use_parquet=False,
    )

    print(f'      Creating IMPORTER_NAME_TOP feature')
    if status is not None: log(f'------Creating IMPORTER_NAME_TOP feature')
    synth_data = creator.generate_importer_top_strata_features(
        df=synth_data,
        dt_train=dt_train,
        max_strat_count=50,
        min_action_rate=0.02,
        min_records=5,
        use_parquet=False,
    )

    print(f'      Creating Quantity Binary Features')
    if status is not None: log(f'------Creating Quantity Binary Features')
    # Fall back to CSV if needed (smaller data, compatibility)
    key_col = "RISK_UNIT"
    quantity_binary_variables = creator.generate_quantity_binaries(
        df=synth_data,
        quantity_threshold=200,
        group_cols=[key_col],
        use_parquet=False
    )

    # Identify non-key columns coming from quantity_binary_variables
    new_cols = [c for c in quantity_binary_variables.columns if c != key_col]

    # Drop any of those columns from synth_data if they already exist
    cols_to_drop = [c for c in new_cols if c in synth_data.columns]
    if cols_to_drop:
        synth_data = synth_data.drop(columns=cols_to_drop)

    # 4. Merge – no name conflict → no _x/_y suffixes
    # TODO: Avoid using merge for larger dataframes
    synth_data = synth_data.merge(
        quantity_binary_variables,
        on=key_col,
        how='left',
    )

    print(f'      Done')
    if status is not None: log(f'------Done')
    return synth_data
