[[pages]]
path = "frontend.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "pages/1_Consignment_Generation.py"
name = "Page 1 - Consignment Generation"
icon = ":package:"

[[pages]]
path = "pages/2_Contamination_Fit.py"
name = "Page 2 - Contamination Fit"
icon = ":test_tube:"

[[pages]]
path = "pages/3_Inspection_Process.py"
name = "Page 3 - Inspection Process"
icon = ":mag_right:"

[[pages]]
path = "pages/4_Scenario_Experiments.py"
name = "Page 4 - Scenario & Experiment Builder"
icon = ":test_tube:"

[[pages]]
path = "pages/5_Run_Simulation.py"
name = "Page 5 - Run Simulation"
icon = ":arrow_forward:"
